name: Dokka

on:
  release:
    types: [published]

jobs:
  publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Build documentation
        run: ./gradlew Ao:dokkaHtml
        env:
          releaseName: ${{ github.event.release.name }}

      - name: Ignore .gitignore
        run: rm -rf ${{ github.workspace }}/.gitignore

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: ${{ github.workspace }}/So/build/dokka/html/